services:
  postgres:
    container_name: postgres_container
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=leaderboard_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    container_name: backend_container
    build:
      context: ./leaderboard/leaderboard_be
      dockerfile: Dockerfile
    ports:
      - "8234:8234"
    working_dir: /app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://admin:pass123@postgres:5432/leaderboard_db
    depends_on:
      - postgres

  frontend:
    container_name: frontend_container
    build:
      context: ./leaderboard/leaderboard_fe
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
volumes:
  pgadmin-data:
  postgres-data: